var us = { 
	"cc_interaction_title":"Live Chat - Support - ABC_Company",
  	"waiting_close":"Cancel",
	"agent_image_alt_text":"Specialist picture",
	"agent_profile_alt_text":"Specialist profile",
	"close_chat_and_take_survey":"End Chat",
    "chat_text_welcomemsg":"You\'re chatting with {0}. Your case number is {1}.",
    "chat_text_welcomemsg_nocaseid":"You\'re now chatting with {0}.",
	"chat_input_description_when_empty":"Type something...",
	"send_message_when_chat_is_over":"You are currently not in a chat",
	"next":"Chat Now",
	//code for Nova 
	"omniture_prop1":"Felix-Chat-Program",
	"omniture_channel":"www.us.support",
	"omniture_pretitle":"acs::chat::",
	"omniture_posttitle":" (US)",
	"omniture_titleforae":"ExpressLane",
	//#Case Lookup Page Keys -Need to changed by business
	"caselookup_comfirmationlink":"Create a new case.",
	"caselookup_mainheadergreeting":"Chat About a Previous Case",
	"caselookup_subheadergreeting":"Please enter the following case information to chat about a previous case:",
	"caselookup_moreinfoonissue":"Please tell us more about why you are contacting ABC_Company: ",
	"caselookup_caseid":"Case ID: ",
	"caselookup_emailaddress":"Email address: ",
	"caselookup_appendedmsg":"or  ",
	"omniture_chatwindowtitle":"Live Chat - Support - ABC_Company",
	"omniture_onholdtitle":"Live Chat - Support - ABC_Company",
	"chatwindow_maxlengtherrormsg":"You can send a maximum of 1024 characters per message.",
	"chatwindow_advisorendgreeting":"Thank you for chatting with us today",
	//#OnHold Window Messages",
	"onhold_existingewtmsg":"Connecting...",
	"onhold_existingewtmsginfo":"Updating estimated wait time...",
	//#Dummy Keys
	"validation_mandatorymsgjp":" ",
	"validation_selectoptionmsgjp":" ",
	"validation_validemailmsgjp":" ",
	"validation_validalphabetsmsgjp":" ",
	"validation_validnumericmsgjp":" ",
	"validation_optionselectionmsgjp":" ",
	"ac_greetingfr":"",
	"ac_headermsgfr":"",
	"ac_requiredfr":"",
	"validation_mandatorymsgfr":"",
	"validation_validemailmsgfr":"",
	"validation_validalphabetsmsgfr":"",
	"validation_validnumericmsgfr":"",
	"validation_optionselectionmsgfr":"",
	//# Script File Keys
	"waitingMessage":"We’re connecting you to an Advisor.",
	"msg_lessthan5":"An Advisor will be with you in a moment.<br> We look forward to helping you.",
	"msg_lessthan10":"An Advisor will be with you in a moment.<br> We look forward to helping you.",
	"msg_lessthan100":"An Advisor will be with you in a few minutes.<br> We look forward to helping you.",
	"msg_defaultewtmessage":"We are experiencing longer than usual wait times. An Advisor will be with you in a few minutes. We look forward to helping you.",
	"msg_postchatsurveyurl":"http://bisurtest.corp.ABC_Company.com/FelixDispatch/felixdispatch?",
	"validation_mandatorymsg":"This is a Required field.",
	"validation_selectoptionmsg":"Please select one of the above options..",
	"validation_validemailmsg":"Please enter a valid email address. For example fred@domain.com",
	"validation_validalphabetsmsg":"Please use letters only (a-z) in this field.",
	"validation_validnumericmsg":"Please enter numeric values only.",
	"validation_optionselectionmsg":"Please make a selection",
	"webchat_titlefornewmsg":"[ New Message ] ",
	//#Keys for Error Conditions , Error and Functional display messages 
	"error_usernotinsession":"No such user in the session",
	"error_usernotexists":"No such user exists",
	"error_chatfinished":"Chat was finished",
	"error_servererror":"Sorry, but your chat ended because of a server issue.",
	//#//# Email attachment - English
	"error_unsupportedfile":"Invalid file type selected. The following file types are accepted: BMP, DOC, DOCX, GIF, GZ, JPG, JPEG, PAGES, PDF, PNG, RAR, RTF, TIF, TIFF, TXT, ZIP.",
	"error_excceedtotalsize":"The total size of your attachment can not exceed 15MB.",
	"display_uploadprocess1":"The file {0} is uploading.",
	"display_uploadprocess2":"",
	"display_uploadsuccess1":"The file {0} was successfully uploaded.",
	"display_uploadsuccess2":"",
	"display_uploadfailed1":"An error occurred while sending the file.",
	"display_uploadfailed2":"Please try again.",
	
	//# for Reconnect functionality after warning timer end chat
	"reconnect_title":"Reconnect",
	"display_chatendedmsg":"Your session has ended. Thanks for chatting with us.",
	"display_fairwarningmsg":"Your chat has been ended by your chat Advisor due to a lack of response.",
	"display_tempunavailablemsg":"Chat support isn’t currently available. Please try later.",
	"display_abandonmsg":"Your chat ended because of a temporary system issue. Please wait while we connect you with the next available Advisor.",
	"display_agentconnectingmsg":"You’re being connected to another Advisor.",
	"display_advisor":"Advisor",
	"display_customer":"Customer",
	"display_privacypolicy":" Privacy Policy",
	//#Need to decide the value for the key by business and the Key
	"display_advisorgroup":"MobileMeGroup",
	"display_inqueuemsg":"<b>All ABC_CompanyCare MobileMe Advisors are busy taking other chats.An ABC_CompanyCare MobileMe Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"privatepolicy_link":"http://www.ABC_Company.com/legal/privacy/",
	"display_casenumber":"Case Number",
	//"display_textblockmaxmsg":"Maximum character limit reached.",
	//"display_charremainingmsg":"characters remaining",
	"defaultparameters_missingmsg":"We&#39;re sorry, but we&#39;re unable to complete the request. Please try again later.",
	"defaulterror_msg":"We&#39;re sorry, but we&#39;re unable to complete the request using that link. You may return to the chat session by following the link in the Express Lane email from ABC_Company.",
	"genericerror_msg":"We&#39;re sorry, but there has been an error. Please try again later.",
	//#GCRM Exceptional Error Messages
	"error_casecreationexception":"We&#39;re sorry, but we are unable to complete your request at this time ",
	"error_duplicatecasecreationexception":"We&#39;re sorry, but we are unable to complete your request at this time ",
	//#Case Lookup Exception
	"error_authenticationException":"We&#39;re sorry, but we are unable to complete your request at this time. Please try again in a few minutes or ",
	"error_unknownException":"We&#39;re sorry, but we are unable to complete your request at this time. Please try again in a few minutes or ",
	"error_invalidcaseException":"We&#39;re sorry, but that case number was not found. Please check your information and try again, or ",
	"error_authorizationException":"We&#39;re sorry, but the case number and email address do not match. Please check your information and try again, or ",
	"error_xmlblankException":"Please enter your case number and try again, or ",
	"error_invalidcustomertypeException":"We&#39;re sorry, but we are unable to complete your request at this time. Please try again in a few minutes or ",
	"error_emptyfirstnamelastnameException":"We&#39;re sorry, but we are unable to complete your request at this time. Please try again in a few minutes or ",
	"error_emptyemailidException":"We&#39;re sorry, but we are unable to complete your request at this time. Please try again in a few minutes or ",
	//# unstaffed Message
	"AC_JPN_EN_iTS_Chat_Queue_Message":"<b>All ABC_CompanyCare iTunes Store Tier 2 Advisors are busy taking other chats. An ABC_CompanyCare iTS Tier 2  Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_CMN_iTS_Tier2_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare Pacific iTunes Chat Support is currently closed.  </b><br><br>ABC_CompanyCare Pacific iTunes Chat Support hours of operation are 09:00 - 18:00 SST 7 days a week.<br><br><b>Thank you for using ABC_CompanyCare iTunes Chat Support.</b><br><br>",
	"AC_PAC_CMN_iTS_Tier2_Queue_Message":"<b>All ABC_CompanyCare iTunes Store Tier 2 Advisors are busy taking other chats. An ABC_CompanyCare iTS Tier 2  Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_CMN_iTS_Tier2_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_PAC_EN_MobileMe_Chat_Queue_Message":"<b>All ABC_CompanyCare MobileMe Advisors are busy taking other chats. An ABC_CompanyCare MobileMe Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_EN_MobileMe_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_MobileMe_Chat_Queue_Message":"<b>All ABC_CompanyCare MobileMe Advisors are busy taking other chats. An ABC_CompanyCare MobileMe Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_MobileMe_Chat_Unstaffed_Message":"<b>Hello, no Advisors are currently available to assist you via chat.  Please try again later.</b>",
	"AC_US_EN_iTS_Chat_AH_Message":"<b>Hello. iTunes Store chat support is currently closed. Please try again between 8:00 a.m. and 8:00 p.m. central. Thank you for using iTunes chat support.</b><br>",
	"AC_US_EN_iTS_Chat_Holiday_Message":"<b>Hello,  iTunes Store Support is currently closed in Observance of the Holiday.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_iTS_Chat_Queue_Message":"<b>All ABC_CompanyCare iTunes Store Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_iTS_Chat_Unstaffed_Message":"<b>Hello, no Advisors are currently available to assist you via chat.  Please try again later.</b><br>",
	"AC_US_EN_iTS_Consult_Chat_AH_Message":"<b>Hello. iTunes Store chat support is currently closed. Please try again between 7:30 a.m. and 8:00 p.m. central. Thank you for using iTunes chat support.</b><br>",
	"AC_US_EN_iTS_Fraud_Chat_AH_Message":"<b>Hello. iTunes Store chat support is currently closed. Please try again between 4:00 a.m. and 10:00 p.m. Central - Monday through Friday or 9:00am and 6:00pm Saturday and Sunday. Thank you for using iTunes chat support.</b><br>",
	//#Added keys for  Unstaffed Message & Interaction type properties
	"AC_EMEA_EN_AA_Chat_AH_Message":"<b>Thank you for contacting Agreement Administration, Europe Support via Chat.</b><br><br>Unfortunately, chat support is not available at this time.<br><br>Our hours of support are M-Sa, 12M - 11AM PT.<br><br>Please contact us during our normal support hours.<br><br><br>",
	"AC_EMEA_EN_AA_Chat_Queue_Message":"<b>All ABC_CompanyCare Agreement Administration Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_EMEA_EN_AA_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_EMEA_EN_CR_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare EMEA Customer Relations Chat Support is currently closed.  </b><br><br>ABC_CompanyCare EMEA Customer Relations hours of operation are 07:00 - 20:00 WET Monday through Friday.<br><br>Thank you for using ABC_CompanyCare Customer Relations chat support.<br><br>",
	"AC_EMEA_EN_CR_Chat_Queue_Message":"<b>All ABC_CompanyCare Customer Relations Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_EMEA_EN_CR_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_EMEA_EN_RTC_Support_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare RTC chat support is currently closed.  EMEA RTC Chat Support is open 07:00 - 20:30 WET Monday - Friday and 08:00 - 16:30 WET Saturday and Sunday.</b><br><br><b>Thank you for using ABC_CompanyCare RTC chat support.</b><br><br>",
	"AC_EMEA_EN_RTC_Support_Chat_Queue_Message":"<b>All ABC_CompanyCare RTC Support Advisors are busy taking other chats. An ABC_CompanyCare RTC Support Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_EMEA_EN_RTC_Support_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_Global_EN_ACORTC_Chat_Queue_Message":"<b>Thank you for contacting ACORTC, we are working hard to get to your chat.  Please continue to hold and an RTC Analyst will be with you as soon as possible.</b><br><b>Thank you for your patience.</b><br>",
	"AC_Global_EN_ACORTC_Chat_Unstaffed_Message":"<b>Hello, We are unavailable at this time, please try to chat us again in five minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_Global_EN_ACORTC_VTO_Chat_Disclaimer_Message":"<b>  If you need training time, please end this chat now and start a new chat under the support and questions option. </b><br><b>If no training time is needed, please continue to hold. Thank you.</b><br>",
	"AC_Global_EN_ACORTC_VTO_Chat_Queue_Message":"<b>All chats are handled in order received.  Please be aware that due to the number of Advisors applying for Voluntary Time Off or Early Outs, when your chat is answered we may no longer have any remaining space. </b> Advisors are responsible for ensuring they are okay to leave before applying for any Voluntary Time Off or Early Outs.  Training is always to be at 100% completion before you apply.  <br><br><b> Thank you for your patience.</b><br><br>",
	"AC_Global_EN_ACORTC_VTO_Chat_Unstaffed_Message":"<b>At this time we are unable to assist with any Voluntary Time Off or Early Outs request. </b> If you are getting this message and we have sent out an email announcing availably of Voluntary Time Off or Early Outs, please try again in five minutes. <br><br><b> If no email was sent, please remember that only when first alerted that your queue has time available will we be online to process your request. Thank you.</b><br><br>",
	"AC_Global_EN_ADS_Developer_Chat_Queue_Message":"<b>Thank you for contacting ADSDev Support, we are working hard to get to your chat.  Please continue to hold and a Dev Support Advisor will be with you as soon as possible.</b><br><b>All chats are handled in order received.  Please be aware that due to the number of Advisors asking for support, before your chat is answered we need to have Names, PID, the details of your Issue, SONAR #, what resources you have checked prior to escalating, and proposed action, etc.</b><br>",
	"AC_Global_EN_ADS_Developer_Chat_Unstaffed_Message":"<b>At this time we are unable to assist with any chat requests. If you are getting this message between the hours of 8:00 AM and 8:00 PM CST please try again after five minutes. </b><br><b>Thank you.</b><br>",
	"AC_JPN_EN_iTS_Chat_Queue_Message":"<b>All ABC_CompanyCare iTunes Store Tier 2 Advisors are busy taking other chats. An ABC_CompanyCare iTS Tier 2  Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_CMN_iTS_Tier2_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare Pacific iTunes Chat Support is currently closed.  </b><br><br>ABC_CompanyCare Pacific iTunes Chat Support hours of operation are 09:00 - 18:00 SST 7 days a week.<br><br><b>Thank you for using ABC_CompanyCare iTunes Chat Support.</b><br><br>",
	"AC_PAC_EN_AA_Chat_AH_Message":"<b>Thank you for contacting Agreement Administration, Asia/Pacific Support via Chat.</b><br><br>Unfortunately, chat support is not available at this time. <br><br>Our hours of support are M-F, 09:00 - 21:00 AET.<br><br>Please contact us during our normal support hours.<br><br><br>",
	"AC_PAC_EN_AA_Chat_Queue_Message":"<b>All ABC_CompanyCare Agreement Administration Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_EN_AA_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_PAC_EN_Dispatch_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare Pacific Dispatch Chat Support is currently closed.  </b><br><br><b>Thank you for using ABC_CompanyCare Dispatch chat support.</b><br><br>",
	"AC_PAC_EN_Dispatch_Chat_Queue_Message":"An Advisor will be with you momentarily. We look forward to answering your questions.",
	"AC_PAC_EN_RTC_Support_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare Pacific RTC Chat Support is currently closed.  ABC_CompanyCare Pacific RTC hours of operation are 06:00 - 21:00 SST Monday through Friday, 09:00 - 19:00 SST Saturday and Sunday.</b>",
	"AC_PAC_EN_RTC_Support_Chat_Queue_Message":"<b>All ABC_CompanyCare RTC Support Advisors are busy taking other chats. An ABC_CompanyCare RTC Support Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_PAC_EN_RTC_Support_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_ACO_Helpdesk_Chat_AH_Message":"b>Hello.  ABC_CompanyCare Operations Helpdesk Chat Support is currently closed.  </b><br><br>ACO Helpdesk hours of operation are 8:00am - 8:00pm Central Time, Monday through Friday.<br><br><b>Thank you for using ABC_CompanyCare Operations Helpdesk chat support.</b><br><br>",
	"AC_US_EN_ACO_Helpdesk_Chat_Holiday_Message":"<b>Hello, ACO Helpdesk Support is currently closed in observance of the Holiday.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_ACO_Helpdesk_Chat_Meeting_Message":"<b>Thank you for contacting the ACO Helpdesk.</b><br><br><b>At this time we are offline for our weekly staff meeting and will return at 3:30 PM Central time. Thank you.</b><br><br>",
	"AC_US_EN_ACO_Helpdesk_Chat_Queue_Message":"<b>All  ABC_CompanyCare Operations Helpdesk Advisors are busy taking other chats. An ACO Helpdesk  Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_ACO_Helpdesk_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Operations Helpdesk staff are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_CR_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare US Customer Relations Chat Support is currently closed.  </b><br><br>ABC_CompanyCare Customer Relations hours of operation are 8:00am - 8:15pm Central Time Monday through Friday.<br><br><b>Thank you for using ABC_CompanyCare Customer Relations chat support.</b><br><br>",
	"AC_US_EN_CR_Chat_Queue_Message":"<b>All ABC_CompanyCare Customer Relations Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_CR_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_CR_Tier1_Chat_Holiday_Message":"<b>Hello,  Customer Relations is currently closed in observance of the Holiday.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_Dispatch_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare US Dispatch Chat Support is currently closed.  </b><br><br>ABC_CompanyCare Dispatch hours of operation are 8:00am - 8:15pm Central Time Monday through Sunday.<br><br><b>Thank you for using ABC_CompanyCare Dispatch chat support.</b><br><br>",
	"AC_US_EN_Dispatch_Chat_Queue_Message":"<b>All ABC_CompanyCare Dispatch Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_Dispatch_Chat_T1_Holiday_Message":"<b>Hello, Direct Dispatch is currently closed in observance of Labor Day.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_Dispatch_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_EDU_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare US Education Chat Support is currently closed.  </b><br><br><b>ABC_CompanyCare Education hours of operation are 6:00am - 8:00pm Central Time Monday through Friday.</b><br><br><b>Thank you for using ABC_CompanyCare Education chat support.</b><br><br>",
	"AC_US_EN_EDU_Chat_Queue_Message":"<b>All ABC_CompanyCare Education Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_EDU_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_EDU_Contract_Chat_Holiday_Message":"<b>Hello.  ABC_CompanyCare US Education Chat Support is currently closed in Observance of the Holiday.</b><br><br><b>Thank you for using ABC_CompanyCare Education chat support.</b><br><br>",
	"AC_US_EN_RTC_Chat_Holiday_Message":"<b>Hello, RTC Support is currently closed in observance of Labor Day.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_RTC_Support_Chat_AH_Message":"<b>Hello.  ABC_CompanyCare RTC chat support is currently closed.  AMR RTC Chat Support is open from 7:45am - Midnight CST Monday - Friday and 7:45am - 9:00pm Saturday and Sunday.</b><br><br><b>Thank you for using ABC_CompanyCare RTC chat support.</b><br><br>",
	"AC_US_EN_RTC_Support_Chat_Meeting_Message":"<b>Thank you for contacting the AMR ABC_CompanyCare RTC.</b><br><br><b>At this time we are offline for our weekly staff meeting and will return at 5PM Central time. Thank you.</b><br><br>",
	"AC_US_EN_RTC_Support_Chat_Queue_Message":"<b>All ABC_CompanyCare RTC Support Advisors are busy taking other chats. An ABC_CompanyCare RTC Support Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_RTC_Support_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes.</b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_Repair_Status_Chat_AH_Message":"<b>We&#39;re sorry. Chat is not currently available. Please try again later or contact us through another channel.</b><br><br>Please refer to <a href=http://www.ABC_Company.com/support/contact/>ABC_Company Support Contact</a> for alternate contact methods.<br><br>",
	"AC_US_EN_Repair_Status_Chat_Holiday_Message":"<b>We&#39;re sorry. Chat is not currently available. Please try again later or contact us through another channel.</b><br><br>Please refer to <a href=http://www.ABC_Company.com/support/contact/>ABC_Company Support Contact</a> for alternate contact methods.<br><br>",
	"AC_US_EN_Repair_Status_Chat_Queue_Message":"<b>All ABC_CompanyCare Repair Status Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"AC_US_EN_Repair_Status_Chat_Unstaffed_Message":"<b>Hello, ABC_CompanyCare Advisors are currently unavailable to assist you. Normal business hours are 8am - 5pm U.S. central time. </b><br><br><b>Thank you.</b><br><br>",
	"AC_US_EN_Test_Chat_Holiday_Message":"<b>Test Chat Support is open from 7:45am - Midnight CST Monday - Friday and 7:45am - 9:00pm Saturday and Sunday.</b><br><br><b>Thank you.</b><br><br>",
	"AC_EMEA_EN_iTS_Chat_Queue_Message":"<b>All iTS Advisors are currently taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.<b><br><b>Thank you for your patience.</b><br>",
	//#Added keys for  Unstaffed Message & Interaction type properties // need to verify not sure  -- TODO
	"AC_JPN_JA_iOS_Chat_Unstaffed_Message":"Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes. Thank you.",
	"AC_JPN_JA_iOS_Chat_Queue_Message":"All ABC_CompanyCare Advisors are busy taking other chats. An Advisor will join this chat shortly. Thank you for your patience.",
	"AC_JPN_JA_iOS_Chat_AH_Message":"Hello. You have reached us outside of normal operating hours 8AM to 5PM Monday - Friday.  Please try your chat again during business hours. Thank you.",
	"AC_JPN_JA_iOS_Chat_Holiday_Message":"Hello. Chat support is currently closed in observance of the holiday  Please try your chat again tomorrow during normal business hours 8AM to 5PM Monday - Friday. Thank you.",
	"AC_JPN_JA_iOS_Chat_Meeting_Message":"Hello. All Advisors are currently in a team meeting.  Please try your chat again in one hour. Thank you.",
	"AC_JPN_JA_iOS_Chat_Filename_Invalid_Message":"This is an invalid file name. Please do not use any of the following when saving your file:  ..  `  :  ;  /  \  |",
	"AC_PAC_CMN_iOS_Chat_Unstaffed_Message":"Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes. Thank you.",
	"AC_PAC_CMN_iOS_Chat_Queue_Message":"All ABC_CompanyCare Advisors are busy taking other chats. An Advisor will join this chat shortly. Thank you for your patience.",
	"AC_PAC_CMN_iOS_Chat_AH_Message":"Hello. You have reached us outside of normal operating hours 8AM to 5PM Monday - Friday.  Please try your chat again during business hours. Thank you.",
	"AC_PAC_CMN_iOS_Chat_Holiday_Message":"Hello. Chat support is currently closed in observance of the holiday  Please try your chat again tomorrow during normal business hours 8AM to 5PM Monday - Friday. Thank you.",
	"AC_PAC_CMN_iOS_Chat_Meeting_Message":"Hello. All Advisors are currently in a team meeting.  Please try your chat again in one hour. Thank you.",
	"AC_PAC_CMN_iOS_Chat_Filename_Invalid_Message":"This is an invalid file name. Please do not use any of the following when saving your file:  ..  `  :  ;  /  \  |",
	"AC_PAC_YUE_iOS_Chat_Unstaffed_Message":"Hello, ABC_CompanyCare Advisors are currently unavailable to assist you.  Please try your chat again in 15 minutes. Thank you.",
	"AC_PAC_YUE_iOS_Chat_Queue_Message":"All ABC_CompanyCare Advisors are busy taking other chats. An Advisor will join this chat shortly. Thank you for your patience.",
	"AC_PAC_YUE_iOS_Chat_AH_Message":"Hello. You have reached us outside of normal operating hours 8AM to 5PM Monday - Friday.  Please try your chat again during business hours. Thank you.",
	"AC_PAC_YUE_iOS_Chat_Holiday_Message":"Hello. Chat support is currently closed in observance of the holiday  Please try your chat again tomorrow during normal business hours 8AM to 5PM Monday - Friday. Thank you.",
	"AC_PAC_YUE_iOS_Chat_Meeting_Message":"Hello. All Advisors are currently in a team meeting.  Please try your chat again in one hour. Thank you.",
	"AC_PAC_YUE_iOS_Chat_Filename_Invalid_Message":"This is an invalid file name. Please do not use any of the following when saving your file:  ..  `  :  ;  /  \  |",
	"AC_PAC_CMN_RTC_Support_Chat_Queue_Message":"All ABC_CompanyCare RTC Support Advisors are busy taking other chats. An ABC_CompanyCare RTC Support Advisor will join this chat shortly.  Thank you for your patience.",
	"AC_PAC_CMN_RTC_Support_Chat_Unstaffed_Message":"Hello.  Real Time Coordinators are currently unavailable.  Please try your chat again in 15 minutes.",
	"AC_PAC_CMN_RTC_Support_Chat_AH_Message":"Hello. ABC_CompanyCare RTC chat support is currently closed.  RTC Chat Support is open from 9:00am - 9:30PM Monday - Friday and 9:00am - 6:30pm Saturday and Sunday.",
	"AC_PAC_CMN_RTC_Chat_Holiday_Message":"Hello, RTC Support is currently closed in observance of the Holiday.  Thank you.",
	"AC_PAC_CMN_RTC_Support_Chat_Meeting_Message":"Thank you for contacting ABC_CompanyCare RTC.  At this time we are offline for our weekly staff meeting and will return at 4 pm. Thank you.",
	"ac_Education":"Education",
	"ac_RepairStatus":"Repair Status",
	"ac_MobileMe":"MobileMe",
	"ac_RTC":"RTC",
	"ac_DirectDispatch":"Direct Dispatch",
	"ac_CustomerRelations":"Customer Relations",
	"ac_iTSFraud":"iTunes Store Fraud",
	"ac_DeveloperSupport":"Developer Support",
	"ac_AgreementAdmin":"Agreement Admin",
	"ac_USiPod":"US iPod",
	"ac_Test":"Test",
	"ac_iTSTier2":"iTS Tier 2",
	"ac_iTS":"iTunes Store",
	"ac_ACOHelpDesk":"ACO Helpdesk",
	//# Added Keys for MiniME Chat // TODO
	"postChat_msg":" Take Survey",
	"miniMe_desc":"Enter a topic for this chat session:",
	"miniMe_startChat":" Start Chat",
	"miniMe_welcomeMsg":" Welcome to Chat",
	"miniMe_send":"Type a message and tap return",
	"display_info":"This chat will be recorded for quality.",
	"miniMe_failedvalidationmsg":"One or more entries below have errors. Please make corrections and try again. ",
	"onhold_msg_lessthan5":"An Advisor will be with you in a moment.<br> We look forward to helping you.",
	"onhold_msg_lessthan10":"An Advisor will be with you in a moment.<br> We look forward to helping you.",
	"onhold_msg_lessthan100":"An Advisor will be with you in a few minutes.<br> We look forward to helping you.",
	"onhold_msg_defaultewtmessage":"We are experiencing longer than usual wait times. An Advisor will be with you in a few minutes. We look forward to helping you.",
	"miniMewindow_maxlengtherrormsg":"Character limit. Click return to continue.",
	//#QueueSpecific //TODO
	"AC_Global_Abusive_Deferral_Message":"We\'re sorry, but chat support is temporarily unavailable. Please try again later or call 1-800-APL-CARE.",
	"AC_Global_Support_Chat_Queue_Message":"An Advisor will be with you momentarily. We look forward to answering your questions.",
	"AC_Global_Chat_Unstaffed_Message":"<b>We\'re sorry. Chat is not currently available. Please try again later or contact us through another channel.</b><br><br>Please refer to <a href=http://www.ABC_Company.com/support/contact/>ABC_Company Support Contact</a> for alternate contact methods.<br><br>",
	"AC_Global_Chat_AH_Message":"<b>Hello. You have reached us outside of normal operating hours.  Please try your chat again during business hours. Thank you.</b><br>",
	"AC_Global_Chat_Holiday_Message":"<b>Hello, this chat queue is currently closed in observance of the Holiday. Thank you.</b><br>",
	"AC_Global_Chat_Queue_Message":"<b>All ABC_CompanyCare Advisors are busy taking other chats. An ABC_CompanyCare Advisor will join this chat shortly.</b><br><b>Thank you for your patience.</b><br>",
	"error_nofileselected":"No file selected.",
	"error_invalidfilename":"This is an invalid file name. Please do not use any of the following when saving your file:  ..  `  :  ;  /  \  | ! @ # $ % ^ & * ( ) + = ? < > { } [ ]",
	"error_mimeType":"Invalid file type selected. The following file types are accepted: BMP, DOC, DOCX, GIF, GZ, JPG, JPEG, PAGES, PDF, PNG, RAR, RTF, TIF, TIFF, TXT, ZIP.",
	"privacy_message_text":"ABC_Company may record and keep this conversation for quality control and training purposes.",
	"chatEndThankYouMsg":"Your session has ended. Thanks for chatting with us.",
	"error_message_CAS":"We don&#39;t have enough information to complete this request.  If you would like to start a new support session, please close this window and return to the ABC_Company Support page.",
	
	"glance_confirmation_text_pre":"Would you like to view {0}'s device as you talk?",
	"glance_confirmation_text_post":"",
	"screen_confirmation_text_post": "Would you like to view {0}\u2019s article as you talk?",
	"glance_confirmation_accept":"Yes",
	"glance_confirmation_decline":"No, thanks",
	"sc_close_cta_link_copy":"Stop viewing {0}\u2019s screen",
	"chat_iqc_readarticle":"Read Article",
	"iqc_generic_title" : "Top Questions",
	"glance_close_link":"Stop Viewing Device",
	"iqc_chat_onhold_message":"Please wait while we connect you to an Advisor.",
	"shared_space_article_text_pre":"Sharing Article",
	
	"ax_title_sharedspace":"Shared Space Window",
	"ax_title_devicecast":"Device Cast Window",
	"ax_article_opening":"Article Opening",
	"ax_article_closing":"Article Closing",
	"ax_opens_in_new_window":"Opens in new window",
	"ax_title_ABC_CompanyChat":"ABC_Company Chat",
	"ax_interaction_title" : "Live Chat",
	"ax_agent_alt_description":"Now chatting with ",
	"ax_loading_chat":"Loading chat",
	"ax_is_typing":"is typing",
	"ax_agent":"Agent:",
	"ax_customer":"Me:",
	"ax_devicecast_window_opening":"Device Cast Window Opening",
	"ax_devicecast_window_closing":"Device Cast Window Closing",
	"ax_cc_interaction_title":"Questions? Just Ask.",
	/***** K2G *****/
	"display_filescanstatus1":"The file can't be sent because it contains a virus.  Please try a different file.",
	"display_filescanstatus2":" The file ",
	"display_filescanstatus3":" cannot be uploaded.",
	
	"ilogForm_ArticleViewer_Label_EngSecurityWarning":"Issue discovery incomplete. The issue described here may be incorrect and has not been vetted by the company. Use details from this discussion thread with extreme caution, and do not take any steps that would put customer data at risk.",								
	"ilogForm_ArticleViewer_Label_T1Inst":"Tier 1 Instructions",
	"ilogForm_ArticleViewer_Label_SecurityWarning":"ABC_Company Internal Use Only - Issue/Investigation In Progress - Confidential Information - Do Not Disclose Externally",								
	"ilogForm_ArticleViewer_Label_Rating_Helpful":"Helpful",					
	"ilogForm_ArticleViewer_Label_SysRequirements":"System Requirements",								
	"ilogForm_ArticleViewer_Label_Summary":"Summary",							
	"ilogForm_ArticleViewer_Label_PostDate":"Post Date:",								
	"ilogForm_ArticleViewer_Label_mostRelevantContent":"Most Relevant Content",							
	"ilogForm_ArticleViewer_Label_ServProvComment":"Service Provider Comments",								
	"ilogForm_ArticleViewer_Label_mostPopularContent":"Most Popular Tracked Issues",								
	"ilogForm_ArticleViewer_Label_linkedToSimilarCases":"Linked to Similar Cases",
	"ilogForm_ArticleViewer_Label_SupportedLang":"Supported Languages",								
	"ilogForm_ArticleViewer_Label_Rating_SomewhatHelpful":"Somewhat helpful",
	"ilogForm_ArticleViewer_Label_ABC_CompanyIntComments":"ABC_Company Internal Comments",
	"ilogForm_ArticleViewer_Label_DownloadId":"Download ID:",							
	"ilogForm_ArticleViewer_Label_HWIsolation":"Hardware Isolation"	,					
	"ilogForm_ArticleViewer_Label_AddtnlInfo":"Additional Information",
	"ilogForm_ArticleViewer_Label_CPGuidelines":"Before posting questions and comments to this Collaborative Procedure, please see <a href='http://support.ABC_Company.com/kb/cp29'>Guidelines for Using Collaborative Procedures</a>.",
	"ilogForm_ArticleViewer_Label_Collapse":"Collapse All Sections",							
	"ilogForm_ArticleViewer_Label_Resolution":"Resolution",							
	"ilogForm_ArticleViewer_Label_Country":"Country:",								
	"ilogForm_ArticleViewer_Label_SecurityWarningExtn":"Viewable by ABC_Company-Authorized Service Providers/Self-Servicing Accounts",							
	"ilogForm_ArticleViewer_Label_Rating_Solved":"Solved my problem",								
	"ilogForm_ArticleViewer_Label_FileSize":"File Size:",								
	"ilogForm_ArticleViewer_Label_ProdAffected":"Products Affected"	,							
	"ilogForm_ArticleViewer_Label_mostRecentDratContent":"Most Recent Tracked Issues",								
	"ilogForm_ArticleViewer_Label_Archived":"This article has been archived and is no longer updated by ABC_Company",								
	"ilogForm_ArticleViewer_Label_Expand":"Expand All Sections"	,							
	"ilogForm_ArticleViewer_Label_emailToCustomer":"Email to Customer",								
	"ilogForm_ArticleViewer_Label_License":"License:",								
	"ilogForm_ArticleViewer_Label_RelevantContent":"Relevant Content",								
	"ilogForm_ArticleViewer_Label_linkedToCase":"Linked to Case",								
	"ilogForm_ArticleViewer_Label_ACRole":"ABC_CompanyCare Role:",								
	"ilogForm_ArticleViewer_Label_Download":"Download",								
	"ilogForm_ArticleViewer_Label_Rating_ThankU":"Thanks for rating this article",							
	"ilogForm_ArticleViewer_Label_Rating_NotHelpful":"Not helpful",								
	"ilogForm_ArticleViewer_Label_ViewLink":"View &gt;"	,							
	"ilogForm_ArticleViewer_Label_Symptoms":"Symptoms",								
	"ilogForm_ArticleViewer_Label_Rating_VHelpful":"Very helpful",								
	"ilogForm_ArticleViewer_Label_T2Inst":"Tier 2 Instructions"	,							
	"ilogForm_ArticleViewer_Label_Rating_OneMoment":"One Moment Please"	,							
	"ilogForm_ArticleViewer_Label_Qualifications":"Qualifications for Capture",								
	"ilogForm_ArticleViewer_Label_Important":"Important:",							
	"ilogForm_ArticleViewer_Label_RateThisArticle":"Rate this article:",								
	"ilogForm_ArticleViewer_Label_RelevantPreparedResponses":"Relevant Prepared Responses",								
	"ilogForm_ArticleViewer_Label_sendToSharedSp":"Shared with Customer",								
	"ilogForm_ArticleViewer_Stub_DraftSoln":"Draft Solution",								
	"ilogForm_ArticleViewer_Stub_ProbAndTS":"Probing &amp; Troubleshooting",								
	"ilogForm_ArticleViewer_Stub_Comment_Save":"Save",								
	"ilogForm_ArticleViewer_Stub_Resolution":"Resolution",								
	"ilogForm_ArticleViewer_Stub_OriginalCase":"Original Case:",								
	"ilogForm_ArticleViewer_Stub_Issue":"Issue"	,							
	"ilogForm_ArticleViewer_Stub_Security":"Security",								
	"ilogForm_ArticleViewer_Stub_Comment_Cancel":"Cancel",								
	"ilogForm_ArticleViewer_Stub_TSSteps":"Troubleshooting Steps",								
	"ilogForm_ArticleViewer_Stub_OfLbl":"of",								
	"ilogForm_ArticleViewer_Stub_Priority":"Priority:",								
	"ilogForm_ArticleViewer_Stub_MostRecent":"Most Recent",								
	"ilogForm_ArticleViewer_Stub_Reply":"Reply"	,							
	"ilogForm_ArticleViewer_Stub_StubType":"Stub Type",								
	"ilogForm_ArticleViewer_Stub_CaseLinked":"cases linked"	,							
	"ilogForm_ArticleViewer_Stub_AddtnlNotes":"Additional Notes",								
	"ilogForm_ArticleViewer_Stub_AddComment":"Add a Comment",								
	"ilogForm_ArticleViewer_Stub_IssueDesc":"vIssue Description",								
	"ilogForm_ArticleViewer_Stub_IssueLbl":"Issue:"	,							
	"ilogForm_ArticleViewer_Stub_ProdAndConf":"Product &amp; Configuration",								
	"ilog_ArticleViewer_HeaderLabel_referralIdLbl":"Referral ID:",								
	"ilog_ArticleViewer_HeaderLabel_transactionIdLbl":"Transaction ID:",								
	"ilog_ArticleViewer_HeaderLabel_ISCSChannelUneligbleLbl":"You do not have access to iTunes Store Support content based on your security roles listed in Maestro",								
	"ilog_ArticleViewer_HeaderLabel_ISCSExpandedAuthorLbl":"ISCS Expanded Author",								
	"ilog_ArticleViewer_HeaderLabel_ISCSManagementLbl":"ISCS Management",								
	"ilog_ArticleViewer_HeaderLabel_ISCSSSELbl":"ISCS SSE",								
	"ilog_ArticleViewer_HeaderLabel_ISCSStandardAuthorLbl":"ISCS Standard Author",								
	"ilog_ArticleViewer_HeaderLabel_ISCSStandardSectionLbl":"ISCS Standard Section"	,							
	"ilog_ArticleViewer_HeaderLabel_ISCSSeniorSpclSectionLbl":"ISCS Senior Specialist Section",								
	"ilog_ArticleViewer_HeaderLabel_ISCSExpandedSectionLbl":"ISCS Expanded Section",								
	"ilog_ArticleViewer_HeaderLabel_ABC_CompanyCareRoleLbl":"ABC_CompanyCare Role",								
	"ilog_ArticleViewer_HeaderLabel_CountryLbl":"Country",								
	"ilogForm_kcs_createStub_createStubConfirmLbl":"Please save the case before editing the article",								
	"ilogForm_kcs_createStub_successLbl":"Saved Successfully",
	"ilogForm_kcs_createStub_stubKCSEnableLbl":"Issue Tracker content is only available for certain Affected Products.",							
	"ilogForm_kcs_createStub_affProConfirmLbl":"Changing the Affected Product will disable Issue Tracker functionality, and any unsaved Issue Tracker content will be lost.",								
	"ilogForm_kcs_createStub_shortTitleLbl":"Short Title",								
	"ilogForm_kcs_createStub_componentLbl":"Component",								
	"ilogForm_kcs_createStub_framerContentLbl":"Framer Only Content",								
	"ilogForm_kcs_createStub_templateNameLbl":"Visible to Framers Only",								
	"ilogForm_kcs_createStub_cloneIdpro":"AA1",								
	"ilogForm_kcs_createStub_countryAttribute":"COUNTRY.ALL_GEOS",								
	"ilogForm_kcs_createStub_symptomsLbl":"Symptoms",								
	"ilogForm_kcs_createStub_optionLbl":"New Issue Track Post",								
	"ilogForm_kcs_createStub_probingAndTroubleLbl":"Probing &amp Troubleshooting",								
	"ilogForm_kcs_createStub_validateErrMsg":"Please fill all mandatory fields",								
	"ilogForm_kcs_createStub_templateLbl":"Template",								
	"ilogForm_kcs_createStub_cloneIdit":"AA1",								
	"ilogForm_kcs_createStub_additionalInfoLbl":"Additional Information",								
	"ilogForm_kcs_createStub_solutionLbl":"Solution",								
	"ilogForm_kcs_createStub_cloneIdmnt":"AA1",								
	"ilogForm_kcs_createStub_cloneIduat":"AA1",								
	"ilogForm_kcs_createStub_cloneIddev":"AA1",							
	"ilogForm_kcs_createStub_flagDescLbl":"Flag Description",								
	"ilogForm_kcs_createStub_flagTitleLbl":"Flag Title",								
	"ilogForm_kcs_createStub_cloneIdtrn":"AA1",								
	"ilogForm_kcs_createStub_IssueLbl":"Issue",								
	"ilogForm_kcs_createStub_introductionLbl":"Introduction",							
	"ilogForm_kcs_createStub_additionalNotesLbl":"Additional Notes",								
	"ilogForm_kcs_createStub_issueLbl":"Issue",								
	"ilogForm_kcs_createStub_caseTitleLbl":"Issue Title",								
	"ilogForm_kcs_createStub_summaryLbl":"Summary",								
	"ilogForm_kcs_createStub_productAndConfigLbl":"Product &amp Configuration",								
	"ilogForm_ArticleViewer_flagRefresh":	"This article has been modified. Refresh to view changes.",								
	"ilogForm_ArticleViewer_flagBannerMsg":"This article has flag(s) awaiting approval",
	"ilogForm_ArticleViewer_FdbkSubGuideLbl":"Feedback and Submission Guidelines",
	"ilogForm_ArticleViewer_RefreshButtonLbl":"Refresh",
	"ilogForm_ArticleViewer_fallback_heading": "We&#39re sorry.",
	"ilogForm_ArticleViewer_fallback_content": "We can&#39t find the page you&#39re looking for.",
	"ilogForm_ArticleViewer_fallback_content1":"Please return to the <a href='http://www.ABC_Company.com/support' onclick='s_objectID=&quot;http://www.ABC_Company.com/support_1&quot;;return this.s_oc?this.s_oc(e):true'>ABC_Company Support homepage</a>.",
	/*iPad optimization keys*/
	"emailTranscriptMessage":"Would you like us to email you a copy of this chat?",
	"sendEmailTranscript":"Send me a copy",
	//"reject":"No need",
	"reject":"No Thanks",
	"audioNotificationMessage":"We'd like to send you audio notifications during this chat. If you choose to receive audio notifications, make sure your speaker volume is turned up.",
	"enableNotification":"Notify me",
	"charLimitMessage":"Please shorten your message.",
	"ABC_Company_care_chat":"ABC_CompanyCare Chat",
	"new_message_received":"New message received.",
	"chatTranscriptMailed":"Your chat transcript has been emailed to the address you provided: ",
	"chatTranscriptFailure":"Sorry, but we weren't able to email your chat transcript.",
	"landscape":"Please rotate your iPad to use Chat.",
	"error_appendmsg":"Sorry, there is a network issue. Please try again.",
	"error_networkdisconnection":"",
	"network_still_down": "Sorry, but the network is still down. Please try again.",
	"disconnected_from_advisor": "You've been disconnected from the Advisor due to a network issue.",
	"reconnect_to_advisor": "You've been reconnected with the Advisor.",
	"waitingScreenNetworkDisconnect": "Sorry, there is a network issue. Please try to reconnect."
};

us.mobile = {
	"mobile_connected":"You\'re now chatting with {0}.",
	"mobile_connected_caseId":"You\'re chatting with {0}. Your case number is {1}.",
	"mobile_privacy_message":"ABC_Company may record and keep this conversation for quality control and training purposes.",
	"mobile_chat_input_description_when_empty":"Type your message",
	"mobile_c2c_cancel":"Cancel",
	"mobile_send_button":"Send",
	"attachment_virus_detected":"Sorry, but this photo can’t be sent. Please try a different photo.",
	"ax_cc_interaction_title":"Need help? Just ask",
	"mobile_reconnecting":"Reconnecting...",
	"ax_add_a_picture":"Add a picture",
	"ax_Img_added":"Added",
	"preview_image_attachment":"Preview image",
	"user_uploaded_image_added":"Image added",
	"user_uploaded_image":"Uploaded image",
	"attachment_sending":"Sending...",
	"error_unsupportedfile":"Sorry but that’s an invalid file type. Acceptable file types are GIF, JPG, JPEG, PNG.",
	"genericPhotoUploadError":"Sorry, but the photo wasn't sent. Please try again."
};